image: mcr.microsoft.com/dotnet/core/sdk:latest

stages:
    - build
    - deploy

build:
    stage: build
    script:
        - "dotnet build"
    artifacts:
      paths:
        - BlazorApp.csproj

pages:
  stage: deploy
  script:
  - mkdir .public
  - cp -r * .public
  - mv .public public
  - dotnet run

  artifacts:
    paths:
    - public
  only:
  - master